### PR TITLE
Add localization framework and parameterize strings

### PR DESCRIPTION
**Pull request by gonzalpi**
## Description

- Parameterize all localizable strings in `/frontend/src/app/localization.tsx`.
- Implement localization framework in `/frontend/src/app/locale.tsx`.
- Load all strings through methods `getLocalizedString` and `getLocalizedElement`.

## Test Plan
`npm run dev` locally, inspect visualy

### CODE REVIEW

**Review by sofiadparamo — APPROVED** [review]
Lgtm

**Comment by sofiadparamo** [comment]
wtf man

**Review by sofiadparamo — COMMENTED** [review]
🤨

**Review by sofiadparamo — APPROVED** [review]

**Comment by gonzalpi** [comment]
Addresses #7

**Pull request merged**
